# The URL the site will be built for
base_url = "https://kathi-archives.bikathihub.tech"
theme = "serene"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
force_theme = false
sections = [
  { name = "posts", path = "/posts", is_external = false },
  # { name = "tags", path = "/tags", is_external = false },
  # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button

footer_copyright = "© 2025 <your-name>"
footer_credits = true # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
