name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy files to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST_IP_ADDRESS }}
                  username: ${{ secrets.VPS_USERNAME }}
                  port: 22
                  key: ${{ secrets.VPS_PRIV_KEY }}
                  source: "."
                  target: "~/kathi-archives"

            # - name: Stop and remove old container
            #   run: |
            #       CONTAINER_ID=$(docker ps -q --filter "name=kathi-archives")
            #       if [ ! -z "$CONTAINER_ID" ]; then
            #           docker stop $CONTAINER_ID
            #           docker rm $CONTAINER_ID
            #           docker rmi kathi-archives:latest
            #       fi

            - name: Build and run Docker container
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST_IP_ADDRESS }}
                  username: ${{ secrets.VPS_USERNAME }}
                  port: 22
                  key: ${{ secrets.VPS_PRIV_KEY }}
                  script: |
                      cd ~/kathi-archives
                      git submodule init
                      git submodule update
                      docker build -t kathi-archives:latest .
                      docker run -d -p 5300:80 kathi-archives:latest --name kathi-archives
                      cd ~
                      rm -rf ~/kathi-archives
